name: Generate Readme Stats

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      # STEP 1: Create the Mini-SIEM Card
      - name: Mini-SIEM Card
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          template: repository
          user: PwnedByP
          repo: Mini-SIEM
          filename: card-siem.svg
          base: ""
          config_timezone: Europe/Madrid

      # STEP 2: Create the Python Card
      - name: Python Card
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          template: repository
          user: PwnedByP
          repo: Python
          filename: card-python.svg
          base: ""
          config_timezone: Europe/Madrid
