name: Generate Readme Stats

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Mini-SIEM Card
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          user: PwnedByP
          template: repository
          repo: Mini-SIEM
          filename: card-siem.svg
          base: header # This is the "Title" and "Description"
          plugin_lines: yes # Adds the "lines of code" graph
          config_theme: radical
          config_timezone: Europe/Madrid

      - name: Python Card
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          user: PwnedByP
          template: repository
          repo: Python
          filename: card-python.svg
          base: header
          plugin_lines: yes
          config_theme: radical
          config_timezone: Europe/Madrid
